name: PPI-Tinderbox
version: 0.01
abstract: The PPI Tinderbox - Parse every module in CPAN
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
requires:
  perl: 5.005
  PPI: 0.840
  PPI::Processor: 0.06
  CPAN::Processor: 0.03
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
